import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage, Section, List, Callout } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The rules for using Mindmate: who may join, what you may write, what stays yours, and what we do and do not promise.',
};

const UPDATED = '26 August 2026';
const CONTACT = 'rajsinghast03@gmail.com';
/** Fill in before relying on the jurisdiction clause. */
const CITY = '[CITY]';

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated={UPDATED}
      intro={
        <p>
          The rules for using Mindmate, written to be read rather than skipped. By creating an
          account you agree to them. If you do not, please do not use the service.
        </p>
      }
    >
      <Section id="who" heading="Who you are agreeing with">
        <p>
          Mindmate is operated by <strong>Raj Singh</strong>, an individual based in India
          (&ldquo;we&rdquo;, &ldquo;us&rdquo;). It is an independent project, not a company, and it
          is early. Contact:{' '}
          <a href={`mailto:${CONTACT}`} className="text-accent-700 underline underline-offset-2">
            {CONTACT}
          </a>
          .
        </p>
      </Section>

      <Section id="eligibility" heading="You must be 18 or older">
        <p>
          Mindmate is for adults. You must be at least 18 to create an account, and you confirm you
          are when you enter your age. We do not check identity documents, so this is a promise you
          make rather than something we verify. If we learn an account belongs to someone under 18,
          we will remove it.
        </p>
      </Section>

      <Section id="account" heading="Your account">
        <p>
          Keep your password to yourself and your email address current — losing access to your
          email means losing access to your account, since password resets go there. One person, one
          account. Do not impersonate anyone.
        </p>
      </Section>

      <Section id="content" heading="What you write stays yours">
        <p>
          Your Curiosity Profile and your messages belong to you. We claim no ownership of them.
        </p>
        <p>
          You give us only the permission needed to actually run the service: to store your writing,
          to convert it into a form that can be matched against other people, to send it to our AI
          provider so that matching and the resonance text work, and to show the parts described in
          the{' '}
          <Link href="/privacy" className="text-accent-700 underline underline-offset-2">
            Privacy Policy
          </Link>{' '}
          to the people it is meant for. That permission ends when you delete the content or your
          account. We will not sell your writing, publish it, or use it for advertising.
        </p>
        <p>
          You are responsible for what you write, and you confirm you have the right to write it.
        </p>
      </Section>

      <Section id="conduct" heading="How to behave here">
        <p>The whole premise is people talking honestly about what they are curious about. So:</p>
        <List
          items={[
            <>Do not harass, threaten, demean, or stalk anyone.</>,
            <>
              Do not post sexual content involving minors, content that incites violence, or
              anything illegal. There is no version of this where we are lenient.
            </>,
            <>Do not impersonate another person, or misrepresent who you are.</>,
            <>Do not use Mindmate to advertise, recruit, spam, or run a scam.</>,
            <>
              Do not scrape the service, automate accounts, or try to extract other people&rsquo;s
              profile text.
            </>,
            <>
              Do not attempt to bypass the security or privacy controls, or access data that is not
              yours.
            </>,
          ]}
        />
        <p>
          Every conversation has a report and a block. Blocking is immediate, ends the connection,
          and removes that person from your suggestions permanently. Reporting sends it to us.
        </p>
      </Section>

      <Section id="matching" heading="Matching is a suggestion, not a judgement">
        <p>
          The explanation of why two people might get along is generated by an AI model from the two
          Curiosity Profiles. It can be wrong, bland, or read more into a coincidence than is really
          there. Treat it as a conversation starter, not an assessment of compatibility, and
          certainly not advice.
        </p>
        <Callout>
          <p>
            We do not verify that anyone is who they say they are. Mindmate has no identity checks
            and no background checks. Use ordinary judgement — the same you would anywhere online —
            about what you share and whom you meet. If you arrange to meet someone in person, that
            is entirely between you and them, and at your own risk.
          </p>
        </Callout>
      </Section>

      <Section id="enforcement" heading="Suspension and removal">
        <p>
          We may remove content, suspend an account, or close it if it breaks these terms or puts
          other people at risk. Where it is reasonable to do so we will explain why, but for serious
          safety issues we may act first. If you think we have got it wrong, write to us and we will
          look again.
        </p>
      </Section>

      <Section id="availability" heading="What we do not promise">
        <p>
          Mindmate is free and provided as it is. We do not promise it will be available, that
          matching will find anyone, that any part of it is free of faults, or that it will keep
          existing. Features may change or be removed. We may need to take it offline.
        </p>
        <p>
          To the fullest extent the law allows, we exclude implied warranties, and we are not liable
          for indirect or consequential loss, lost opportunities, or anything arising from your
          dealings with another user. Nothing here limits liability that cannot be limited by law —
          including for death or personal injury caused by negligence, or for fraud.
        </p>
      </Section>

      <Section id="termination" heading="Leaving">
        <p>
          You can delete your account at any time from your{' '}
          <Link href="/profile" className="text-accent-700 underline underline-offset-2">
            profile page
          </Link>
          . It is immediate and permanent, and it takes your messages with it — including the ones
          already delivered to other people. The{' '}
          <Link href="/privacy" className="text-accent-700 underline underline-offset-2">
            Privacy Policy
          </Link>{' '}
          sets out exactly what is removed.
        </p>
      </Section>

      <Section id="changes" heading="Changes to these terms">
        <p>
          We may update these terms. The date at the top will change, and for anything significant
          we will tell you in the product. If you keep using Mindmate after a change, you accept the
          new terms.
        </p>
      </Section>

      <Section id="law" heading="Governing law">
        <p>
          These terms are governed by the laws of India. The courts at {CITY} have exclusive
          jurisdiction over any dispute arising from them.
        </p>
      </Section>

      <Section id="contact" heading="Contact">
        <p>
          Anything at all:{' '}
          <a href={`mailto:${CONTACT}`} className="text-accent-700 underline underline-offset-2">
            {CONTACT}
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
